module.exports = {
    'Dev Docs': [
        {
          type: 'autogenerated',
          dirName: 'dev'
        }
      ],
      'Usage Docs': [
        {
          type: 'autogenerated',
          dirName: 'usage'
        }
      ]
}